### ISSUE TITLE
lzo package headers not linked? 

### ISSUE THREAD

**Issue by lotusdew-dushyant-goel** [Ledest/elzo#1]
I am trying to integrate this erlang package https://github.com/Ledest/elzo into my elixir app.
I have tried to `mix compile` the app both on ubuntu and mac system, which is happening without errors.
The ledest/elzo package uses erl_nif (native interface function) which requires me to compile and link the correct C header files into a `_build/dev/lib/lzo/priv` folder of elixir app
I am able to do that too : I am using the follwing commands to succesfuly compile the files:
```
Mac:
gcc -Wall \
    -I /opt/homebrew/Cellar/erlang/25.1.1/lib/erlang/erts-13.1.1/include \
    -I /opt/homebrew/Cellar/lzo/2.10/include \
    -fPIC \
    -bundle -flat_namespace -undefined suppress \
    -o _build/dev/lib/lzo/priv/lzo1.so \
    deps/lzo/c_src/lzo1.c

Ubuntu:
gcc -Wall  \
    -I /usr/local/lib/erlang/usr/include  \
    -I /usr/local/include/lzo \
    -fPIC  \
    -shared \
    -o _build/dev/lib/lzo/priv/lzo1.so \
    deps/lzo/c_src/lzo1.c
```

The headers are from official package builds.
When I run iex -S mix the symbol :lzo1. is available on TAB complete.
however I am getting the following errors on calling any NIF ->

```
Mac:
iex(1)> :lzo1.
15:29:57.677 [warning] The on_load function for module lzo1 returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'dlopen(/Users/dushyantgoel/Documents/Github/decomp/_build/dev/lib/lzo/priv/lzo1.so, 0x0002): symbol not found in flat namespace (___lzo_init_v2)\''}}

Ubuntu:
iex(1)> :lzo1.
15:21:49.829 [warning] The on_load function for module lzo1 returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'/home/a6000/Desktop/decomp/_build/dev/lib/lzo/priv/lzo1.so: undefined symbol: lzo1x_decompress_safe\''}}
 ```
The only link I found on google which was half-way helpful is this:
https://erlang.org/pipermail/erlang-questions/2011-June/059678.html

Any leads on how to solve this issue or what direction to look into?

**Comment by Ledest** [comment]
You need to use liblzo2.

**Comment by lotusdew-dushyant-goel** [comment]
(ubuntu)
```
gcc -Wall  \
    -llzol2
    -fPIC  \
    -shared \
     deps/lzo/c_src/lzo1.c
```     

Just making the fact that I am indeed using lzol2 more exiplicit.. 
still geting the same error
```
14:48:30.154 [warning] The on_load function for module lzo1 returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'/home/a6000/Desktop/decomp/_build/dev/lib/lzo/priv/lzo1.so: undefined symbol: lzo1x_decompress_safe\''}}

```

**Comment by Ledest** [comment]
```
$ nm -D /usr/lib64/liblzo2.so | grep lzo1x_decompress_safe
0000000000013720 T lzo1x_decompress_safe
```
Try proper compile/link command line like this (using system liblzo2):
```
cc -O2 -Wall -fPIC -I"/usr/lib/erlang/lib/erl_interface-4.0.3.1/include" -I"/usr/lib/erlang/erts-11.2.2.17/include" c_src/lzo1.c -llzo2 -shared -L"/usr/lib/erlang/lib/erl_interface-4.0.3.1/lib" -o lzo1.so -lei
```
'-llzo2' must be after all sources.
And why are you not using system liblzo2?
```
apt-get install liblzo2-dev
```
or something similar?

**Comment by lotusdew-dushyant-goel** [comment]
Thank for giving showing me the proper command.
I am able to use the package now.
